### ISSUE TITLE
v2.0.4 Crashing - TypeError: Object #<Object> has no method 'indexOf'

### ISSUE THREAD

**Issue by keyscores** [gterrono/houston#315]
Just updated to the latest version and I'm getting a persistent crash.
Crash goes away when I uninstall.

W20150822-17:53:27.031(-4)? (STDERR) 
W20150822-17:53:27.031(-4)? (STDERR) /Users/USER/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150822-17:53:27.031(-4)? (STDERR) 				throw(ex);
W20150822-17:53:27.031(-4)? (STDERR) 				      ^
W20150822-17:53:27.078(-4)? (STDERR) TypeError: Object #<Object> has no method 'indexOf'
W20150822-17:53:27.079(-4)? (STDERR)     at Function.Db.connect (/Users/USER/.meteor/packages/mongo/.1.1.0.26c4wm++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:2086:10)
W20150822-17:53:27.079(-4)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:173:1)
W20150822-17:53:27.079(-4)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
W20150822-17:53:27.079(-4)? (STDERR)     at sync_collections (packages/houston:admin/server/publications.coffee:70:22)
W20150822-17:53:27.079(-4)? (STDERR)     at __coffeescriptShare (packages/houston:admin/server/publications.coffee:98:3)
W20150822-17:53:27.080(-4)? (STDERR)     at /Users/USER/Desktop/graph/.meteor/local/build/programs/server/boot.js:229:5

**Comment by Kostanos** [comment]
Happens exactly the same to me.

```
W20150822-19:18:32.678(-4)? (STDERR) 
W20150822-19:18:32.678(-4)? (STDERR) /home/kostya/.meteor/packages/meteor-tool/.1.1.4.1bxqrno++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150822-19:18:32.679(-4)? (STDERR) 						throw(ex);
W20150822-19:18:32.679(-4)? (STDERR) 						      ^
W20150822-19:18:32.721(-4)? (STDERR) TypeError: Object #<Object> has no method 'indexOf'
W20150822-19:18:32.722(-4)? (STDERR)     at Function.Db.connect (/home/kostya/.meteor/packages/mongo/.1.1.0.zb7oxo++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:2086:10)
W20150822-19:18:32.722(-4)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:173:1)
W20150822-19:18:32.722(-4)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
W20150822-19:18:32.723(-4)? (STDERR)     at sync_collections (packages/houston:admin/server/publications.coffee:70:22)
W20150822-19:18:32.723(-4)? (STDERR)     at __coffeescriptShare (packages/houston:admin/server/publications.coffee:98:3)
W20150822-19:18:32.723(-4)? (STDERR)     at /home/kostya/Application/delivery/delivery_restaurant/.meteor/local/build/programs/server/boot.js:229:5
=> Exited with code: 8
```

**Comment by samcorcos** [comment]
Seems like latest update caused a problem. Fixing it now.

**Comment by GuillaumeM69** [comment]
same bug:

Your app is crashing. Here's the latest log.


/Users/guillaume/.meteor/packages/meteor-tool/.1.1.4.1xp6ghm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: Object #<Object> has no method 'indexOf'
    at Function.Db.connect (/Users/guillaume/.meteor/packages/mongo/.1.1.0.1ruc6ua++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:2086:10)
    at new MongoConnection (packages/mongo/mongo_driver.js:173:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at sync_collections (packages/houston:admin/server/publications.coffee:70:22)
    at __coffeescriptShare (packages/houston:admin/server/publications.coffee:98:3)
    at /Users/guillaume/boring/app/.meteor/local/build/programs/server/boot.js:229:5
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by almogdesign** [comment]
Me to just updated and now app is crashing

I20150823-15:45:40.923(3)? NODE_ENV=development
W20150823-15:45:41.239(3)? (STDERR) 
W20150823-15:45:41.239(3)? (STDERR) /Users/Almog/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150823-15:45:41.239(3)? (STDERR)                                             throw(ex);
W20150823-15:45:41.239(3)? (STDERR)                                                   ^
W20150823-15:45:41.285(3)? (STDERR) TypeError: Object #<Object> has no method 'indexOf'
W20150823-15:45:41.285(3)? (STDERR)     at Function.Db.connect (/Users/Almog/.meteor/packages/mongo/.1.1.0.26c4wm++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:2086:10)
W20150823-15:45:41.285(3)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:173:1)
W20150823-15:45:41.285(3)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
W20150823-15:45:41.285(3)? (STDERR)     at sync_collections (packages/houston:admin/server/publications.coffee:70:22)
W20150823-15:45:41.286(3)? (STDERR)     at __coffeescriptShare (packages/houston:admin/server/publications.coffee:98:3)
W20150823-15:45:41.286(3)? (STDERR)     at /Users/Almog/Almog_Design/Projects_2015/Spoiler_Alert/RnD/spoiler-alert-app/.meteor/local/build/programs/server/boot.js:229:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by samcorcos** [comment]
@GuillaumeM69 @almogdesign Try updating it again. Should be fixed now

**Comment by almogdesign** [comment]
Good on my end

**Comment by samcorcos** [comment]
@keyscores @Kostanos Should be fixed :) let me know if you run into issues after an update.

**Comment by GuillaumeM69** [comment]
2.0.5 fixe this crash :)
