### ISSUE TITLE
Can't seem to get Houston working

### ISSUE THREAD

**Issue by corysimmons** [gterrono/houston#316]
I ran `meteor add houston:admin` then ran `meteor` and it gave me an error to remove `autopublish`. I removed it and tried `meteor` again and just get this error:

```
[[[[[ ~/Desktop/microscope ]]]]]

=> Started proxy.
=> Started MongoDB.
W20150823-01:47:11.414(-4)? (STDERR)
W20150823-01:47:11.415(-4)? (STDERR) /Users/cory/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150823-01:47:11.415(-4)? (STDERR) 						throw(ex);
W20150823-01:47:11.415(-4)? (STDERR) 						      ^
W20150823-01:47:11.415(-4)? (STDERR) TypeError: Object #<Object> has no method 'indexOf'
W20150823-01:47:11.415(-4)? (STDERR)     at Function.Db.connect (/Users/cory/.meteor/packages/mongo/.1.1.0.26c4wm++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:2086:10)
W20150823-01:47:11.415(-4)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:173:1)
W20150823-01:47:11.415(-4)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
W20150823-01:47:11.415(-4)? (STDERR)     at sync_collections (packages/houston:admin/server/publications.coffee:70:22)
W20150823-01:47:11.415(-4)? (STDERR)     at __coffeescriptShare (packages/houston:admin/server/publications.coffee:98:3)
W20150823-01:47:11.416(-4)? (STDERR)     at /Users/cory/Desktop/microscope/.meteor/local/build/programs/server/boot.js:229:5
=> Exited with code: 8
W20150823-01:47:14.003(-4)? (STDERR)
W20150823-01:47:14.003(-4)? (STDERR) /Users/cory/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150823-01:47:14.003(-4)? (STDERR) 						throw(ex);
W20150823-01:47:14.003(-4)? (STDERR) 						      ^
W20150823-01:47:14.051(-4)? (STDERR) TypeError: Object #<Object> has no method 'indexOf'
W20150823-01:47:14.051(-4)? (STDERR)     at Function.Db.connect (/Users/cory/.meteor/packages/mongo/.1.1.0.26c4wm++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:2086:10)
W20150823-01:47:14.051(-4)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:173:1)
W20150823-01:47:14.051(-4)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
W20150823-01:47:14.051(-4)? (STDERR)     at sync_collections (packages/houston:admin/server/publications.coffee:70:22)
W20150823-01:47:14.051(-4)? (STDERR)     at __coffeescriptShare (packages/houston:admin/server/publications.coffee:98:3)
W20150823-01:47:14.051(-4)? (STDERR)     at /Users/cory/Desktop/microscope/.meteor/local/build/programs/server/boot.js:229:5
=> Exited with code: 8
W20150823-01:47:16.690(-4)? (STDERR)
W20150823-01:47:16.690(-4)? (STDERR) /Users/cory/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150823-01:47:16.691(-4)? (STDERR) 						throw(ex);
W20150823-01:47:16.691(-4)? (STDERR) 						      ^
W20150823-01:47:16.739(-4)? (STDERR) TypeError: Object #<Object> has no method 'indexOf'
W20150823-01:47:16.739(-4)? (STDERR)     at Function.Db.connect (/Users/cory/.meteor/packages/mongo/.1.1.0.26c4wm++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:2086:10)
W20150823-01:47:16.739(-4)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:173:1)
W20150823-01:47:16.739(-4)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
W20150823-01:47:16.739(-4)? (STDERR)     at sync_collections (packages/houston:admin/server/publications.coffee:70:22)
W20150823-01:47:16.740(-4)? (STDERR)     at __coffeescriptShare (packages/houston:admin/server/publications.coffee:98:3)
W20150823-01:47:16.740(-4)? (STDERR)     at /Users/cory/Desktop/microscope/.meteor/local/build/programs/server/boot.js:229:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

Any ideas?

**Comment by samcorcos** [comment]
@corysimmons There was an issue with a version dependency :) Should be fixed now

**Comment by corysimmons** [comment]
Works now! Awesome tool! Exactly what I needed.
