### ISSUE TITLE
Error Making user admin.

### ISSUE THREAD

**Issue by nramaker** [gterrono/houston#331]
Installed Houston into a simple Meteor app, navigated to the admin page and created an account. I'm then shown a page telling me that I'm not an admin, with a large Claim Admin button. Pushing the button has no effect. 

This is what's shown in the console.

I20150929-15:40:01.989(-5)? Exception while invoking method '_houston_make_admin' ReferenceError: check is not defined
I20150929-15:40:01.989(-5)?     at [object Object].Meteor.methods._houston_make_admin (packages/houston_admin/packages/h
ouston_admin.js:347:1)
I20150929-15:40:01.989(-5)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
I20150929-15:40:01.989(-5)?     at livedata_server.js:708:19
I20150929-15:40:01.990(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150929-15:40:01.990(-5)?     at livedata_server.js:706:40
I20150929-15:40:01.990(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150929-15:40:01.990(-5)?     at livedata_server.js:704:46
I20150929-15:40:01.990(-5)?     at tryCallTwo (C:\Users\nramaker\AppData\Local\.meteor\packages\promise\0.5.0\npm\node_m
odules\meteor-promise\node_modules\promise\lib\core.js:45:5)
I20150929-15:40:01.991(-5)?     at doResolve (C:\Users\nramaker\AppData\Local\.meteor\packages\promise\0.5.0\npm\node_mo
dules\meteor-promise\node_modules\promise\lib\core.js:171:13)
I20150929-15:40:01.991(-5)?     at new Promise (C:\Users\nramaker\AppData\Local\.meteor\packages\promise\0.5.0\npm\node_
modules\meteor-promise\node_modules\promise\lib\core.js:65:3)

Here is my version information:

E:\udemy_meteor\faq>meteor list
aldeed:collection2    2.5.0  Automatic validation of insert and update operations on the client and server.
autopublish           1.0.4  (For prototyping only) Publish the entire database to all clients
blaze-html-templates  1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript            0.1.5  Compiler plugin that supports ES2015+ in all .js files
ejson                 1.0.7  Extended and Extensible JSON library
es5-shim              4.1.13  Shims and polyfills to improve ECMAScript 5 support
ewall:foundation      5.5.2  Foundation by ZURB - an advanced responsive web framework
houston:admin         2.0.5  A zero-config Meteor Admin
insecure              1.0.4  (For prototyping only) Allow all database writes from the client
iron:router           1.0.9  Routing specifically designed for Meteor
jquery                1.11.4  Manipulate the DOM using CSS selectors
meteor-base           1.0.1  Packages that every Meteor app needs
mobile-experience     1.0.1  Packages for a great mobile user experience
mongo                 1.1.2  Adaptor for using MongoDB and Minimongo over DDP
session               1.1.1  Session variable
standard-minifiers    1.0.1  Standard minifiers used with Meteor apps by default.
tracker               1.0.9  Dependency tracker to allow reactive callbacks

**Comment by jessenorton** [comment]
I get the same bug too. Here's my version info:

aldeed:collection2    2.5.0  Automatic validation of insert and update operations on the client and server.
autopublish           1.0.4  (For prototyping only) Publish the entire database to all clients
blaze-html-templates  1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript            0.1.4* Compiler plugin that supports ES2015+ in all .js files
ejson                 1.0.7  Extended and Extensible JSON library
es5-shim              4.1.13  Shims and polyfills to improve ECMAScript 5 support
ewall:foundation      5.5.2  Foundation by ZURB - an advanced responsive web framework
houston:admin         2.0.5  A zero-config Meteor Admin
insecure              1.0.4  (For prototyping only) Allow all database writes from the client
iron:router           1.0.9  Routing specifically designed for Meteor
jquery                1.11.4  Manipulate the DOM using CSS selectors
meteor-base           1.0.1  Packages that every Meteor app needs
mobile-experience     1.0.1  Packages for a great mobile user experience
mongo                 1.1.1* Adaptor for using MongoDB and Minimongo over DDP
session               1.1.1  Session variable
standard-minifiers    1.0.0* Standard minifiers used with Meteor apps by default.
tracker               1.0.8* Dependency tracker to allow reactive callbacks

**Comment by keyscores** [comment]
+1 this happens on Meteor 1.2.0.2

**Comment by zhaoyao91** [comment]
+1 this happens on Meteor 1.2.0.2

**Comment by rickyPanzer** [comment]
+1 this happens on Meteor 1.2.0.2

**Comment by adrianbadarau** [comment]
@nramaker Had a similar issue, I fixed it adding the check package using meteor add check

**Comment by designorant** [comment]
Thanks @adrianbadarau!
